project_id = "eyioyqtarlikggdlcvth"

[functions.parse-scholarship]
verify_jwt = false

[functions.essay-assistant]
verify_jwt = false

[functions.ai-advisor]
verify_jwt = false

[functions.parse-cv]
verify_jwt = false

[functions.success-meter]
verify_jwt = false

[functions.ai-recommender]
verify_jwt = false

[functions.ai-community-assist]
verify_jwt = false

[functions.pipeline-insights]
verify_jwt = false
